package com.acquire.shopick.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BRANDS".
 */
public class Brands {

    private Long id;
    private String name;
    private String logo_url;
    private String tagline;
    private String category;
    private Long category_id;
    private Boolean liked;
    private Boolean dirty;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Brands() {
    }

    public Brands(Long id) {
        this.id = id;
    }

    public Brands(Long id, String name, String logo_url, String tagline, String category, Long category_id, Boolean liked, Boolean dirty) {
        this.id = id;
        this.name = name;
        this.logo_url = logo_url;
        this.tagline = tagline;
        this.category = category;
        this.category_id = category_id;
        this.liked = liked;
        this.dirty = dirty;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLogo_url() {
        return logo_url;
    }

    public void setLogo_url(String logo_url) {
        this.logo_url = logo_url;
    }

    public String getTagline() {
        return tagline;
    }

    public void setTagline(String tagline) {
        this.tagline = tagline;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Long getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    public Boolean getLiked() {
        return liked;
    }

    public void setLiked(Boolean liked) {
        this.liked = liked;
    }

    public Boolean getDirty() {
        return dirty;
    }

    public void setDirty(Boolean dirty) {
        this.dirty = dirty;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
