package com.acquire.shopick.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.acquire.shopick.dao.UserDao;
import com.acquire.shopick.dao.TopCategoriesDao;
import com.acquire.shopick.dao.CategoriesDao;
import com.acquire.shopick.dao.BrandsDao;
import com.acquire.shopick.dao.StoreDao;
import com.acquire.shopick.dao.PostDao;
import com.acquire.shopick.dao.ProductDao;
import com.acquire.shopick.dao.BrandUpdatesDao;
import com.acquire.shopick.dao.TipsDao;
import com.acquire.shopick.dao.RelatedProductsDao;
import com.acquire.shopick.dao.PostCollectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 8): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 8;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UserDao.createTable(db, ifNotExists);
        TopCategoriesDao.createTable(db, ifNotExists);
        CategoriesDao.createTable(db, ifNotExists);
        BrandsDao.createTable(db, ifNotExists);
        StoreDao.createTable(db, ifNotExists);
        PostDao.createTable(db, ifNotExists);
        ProductDao.createTable(db, ifNotExists);
        BrandUpdatesDao.createTable(db, ifNotExists);
        TipsDao.createTable(db, ifNotExists);
        RelatedProductsDao.createTable(db, ifNotExists);
        PostCollectionDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UserDao.dropTable(db, ifExists);
        TopCategoriesDao.dropTable(db, ifExists);
        CategoriesDao.dropTable(db, ifExists);
        BrandsDao.dropTable(db, ifExists);
        StoreDao.dropTable(db, ifExists);
        PostDao.dropTable(db, ifExists);
        ProductDao.dropTable(db, ifExists);
        BrandUpdatesDao.dropTable(db, ifExists);
        TipsDao.dropTable(db, ifExists);
        RelatedProductsDao.dropTable(db, ifExists);
        PostCollectionDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UserDao.class);
        registerDaoClass(TopCategoriesDao.class);
        registerDaoClass(CategoriesDao.class);
        registerDaoClass(BrandsDao.class);
        registerDaoClass(StoreDao.class);
        registerDaoClass(PostDao.class);
        registerDaoClass(ProductDao.class);
        registerDaoClass(BrandUpdatesDao.class);
        registerDaoClass(TipsDao.class);
        registerDaoClass(RelatedProductsDao.class);
        registerDaoClass(PostCollectionDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
