package com.acquire.shopick.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.acquire.shopick.dao.User;
import com.acquire.shopick.dao.TopCategories;
import com.acquire.shopick.dao.Categories;
import com.acquire.shopick.dao.Brands;
import com.acquire.shopick.dao.Store;
import com.acquire.shopick.dao.Post;
import com.acquire.shopick.dao.Product;
import com.acquire.shopick.dao.BrandUpdates;
import com.acquire.shopick.dao.Tips;
import com.acquire.shopick.dao.RelatedProducts;
import com.acquire.shopick.dao.PostCollection;

import com.acquire.shopick.dao.UserDao;
import com.acquire.shopick.dao.TopCategoriesDao;
import com.acquire.shopick.dao.CategoriesDao;
import com.acquire.shopick.dao.BrandsDao;
import com.acquire.shopick.dao.StoreDao;
import com.acquire.shopick.dao.PostDao;
import com.acquire.shopick.dao.ProductDao;
import com.acquire.shopick.dao.BrandUpdatesDao;
import com.acquire.shopick.dao.TipsDao;
import com.acquire.shopick.dao.RelatedProductsDao;
import com.acquire.shopick.dao.PostCollectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig topCategoriesDaoConfig;
    private final DaoConfig categoriesDaoConfig;
    private final DaoConfig brandsDaoConfig;
    private final DaoConfig storeDaoConfig;
    private final DaoConfig postDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig brandUpdatesDaoConfig;
    private final DaoConfig tipsDaoConfig;
    private final DaoConfig relatedProductsDaoConfig;
    private final DaoConfig postCollectionDaoConfig;

    private final UserDao userDao;
    private final TopCategoriesDao topCategoriesDao;
    private final CategoriesDao categoriesDao;
    private final BrandsDao brandsDao;
    private final StoreDao storeDao;
    private final PostDao postDao;
    private final ProductDao productDao;
    private final BrandUpdatesDao brandUpdatesDao;
    private final TipsDao tipsDao;
    private final RelatedProductsDao relatedProductsDao;
    private final PostCollectionDao postCollectionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        topCategoriesDaoConfig = daoConfigMap.get(TopCategoriesDao.class).clone();
        topCategoriesDaoConfig.initIdentityScope(type);

        categoriesDaoConfig = daoConfigMap.get(CategoriesDao.class).clone();
        categoriesDaoConfig.initIdentityScope(type);

        brandsDaoConfig = daoConfigMap.get(BrandsDao.class).clone();
        brandsDaoConfig.initIdentityScope(type);

        storeDaoConfig = daoConfigMap.get(StoreDao.class).clone();
        storeDaoConfig.initIdentityScope(type);

        postDaoConfig = daoConfigMap.get(PostDao.class).clone();
        postDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        brandUpdatesDaoConfig = daoConfigMap.get(BrandUpdatesDao.class).clone();
        brandUpdatesDaoConfig.initIdentityScope(type);

        tipsDaoConfig = daoConfigMap.get(TipsDao.class).clone();
        tipsDaoConfig.initIdentityScope(type);

        relatedProductsDaoConfig = daoConfigMap.get(RelatedProductsDao.class).clone();
        relatedProductsDaoConfig.initIdentityScope(type);

        postCollectionDaoConfig = daoConfigMap.get(PostCollectionDao.class).clone();
        postCollectionDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        topCategoriesDao = new TopCategoriesDao(topCategoriesDaoConfig, this);
        categoriesDao = new CategoriesDao(categoriesDaoConfig, this);
        brandsDao = new BrandsDao(brandsDaoConfig, this);
        storeDao = new StoreDao(storeDaoConfig, this);
        postDao = new PostDao(postDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        brandUpdatesDao = new BrandUpdatesDao(brandUpdatesDaoConfig, this);
        tipsDao = new TipsDao(tipsDaoConfig, this);
        relatedProductsDao = new RelatedProductsDao(relatedProductsDaoConfig, this);
        postCollectionDao = new PostCollectionDao(postCollectionDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(TopCategories.class, topCategoriesDao);
        registerDao(Categories.class, categoriesDao);
        registerDao(Brands.class, brandsDao);
        registerDao(Store.class, storeDao);
        registerDao(Post.class, postDao);
        registerDao(Product.class, productDao);
        registerDao(BrandUpdates.class, brandUpdatesDao);
        registerDao(Tips.class, tipsDao);
        registerDao(RelatedProducts.class, relatedProductsDao);
        registerDao(PostCollection.class, postCollectionDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        topCategoriesDaoConfig.getIdentityScope().clear();
        categoriesDaoConfig.getIdentityScope().clear();
        brandsDaoConfig.getIdentityScope().clear();
        storeDaoConfig.getIdentityScope().clear();
        postDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
        brandUpdatesDaoConfig.getIdentityScope().clear();
        tipsDaoConfig.getIdentityScope().clear();
        relatedProductsDaoConfig.getIdentityScope().clear();
        postCollectionDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public TopCategoriesDao getTopCategoriesDao() {
        return topCategoriesDao;
    }

    public CategoriesDao getCategoriesDao() {
        return categoriesDao;
    }

    public BrandsDao getBrandsDao() {
        return brandsDao;
    }

    public StoreDao getStoreDao() {
        return storeDao;
    }

    public PostDao getPostDao() {
        return postDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public BrandUpdatesDao getBrandUpdatesDao() {
        return brandUpdatesDao;
    }

    public TipsDao getTipsDao() {
        return tipsDao;
    }

    public RelatedProductsDao getRelatedProductsDao() {
        return relatedProductsDao;
    }

    public PostCollectionDao getPostCollectionDao() {
        return postCollectionDao;
    }

}
