package com.acquire.shopick.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "POST".
 */
public class Post {

    private Long localId;
    private Long id;
    private String globalID;
    private String localFileUri;
    private String username;
    private String user_image;
    private Long user_id;
    private String storename;
    private Long store_id;
    private String categoryname;
    private Long category_id;
    private String brandname;
    private Long brand_id;
    private String brand_logo;
    private String image_url;
    private String title;
    private String description;
    private Long likes;
    private Integer post_type;
    private Integer order_in_category;
    private Boolean favorited;
    private Boolean isLocal;
    private String category;
    private Boolean liked;
    private Boolean dirty;
    private String featured_in_globalID;
    private String featured_in_title;
    private Boolean read;

    // KEEP FIELDS - put your custom fields here
    public static final String LOCAL_ID_PREFIX = "local_";
    // KEEP FIELDS END

    public Post() {
    }

    public Post(Long localId) {
        this.localId = localId;
    }

    public Post(Long localId, Long id, String globalID, String localFileUri, String username, String user_image, Long user_id, String storename, Long store_id, String categoryname, Long category_id, String brandname, Long brand_id, String brand_logo, String image_url, String title, String description, Long likes, Integer post_type, Integer order_in_category, Boolean favorited, Boolean isLocal, String category, Boolean liked, Boolean dirty, String featured_in_globalID, String featured_in_title, Boolean read) {
        this.localId = localId;
        this.id = id;
        this.globalID = globalID;
        this.localFileUri = localFileUri;
        this.username = username;
        this.user_image = user_image;
        this.user_id = user_id;
        this.storename = storename;
        this.store_id = store_id;
        this.categoryname = categoryname;
        this.category_id = category_id;
        this.brandname = brandname;
        this.brand_id = brand_id;
        this.brand_logo = brand_logo;
        this.image_url = image_url;
        this.title = title;
        this.description = description;
        this.likes = likes;
        this.post_type = post_type;
        this.order_in_category = order_in_category;
        this.favorited = favorited;
        this.isLocal = isLocal;
        this.category = category;
        this.liked = liked;
        this.dirty = dirty;
        this.featured_in_globalID = featured_in_globalID;
        this.featured_in_title = featured_in_title;
        this.read = read;
    }

    public Long getLocalId() {
        return localId;
    }

    public void setLocalId(Long localId) {
        this.localId = localId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGlobalID() {
        return globalID;
    }

    public void setGlobalID(String globalID) {
        this.globalID = globalID;
    }

    public String getLocalFileUri() {
        return localFileUri;
    }

    public void setLocalFileUri(String localFileUri) {
        this.localFileUri = localFileUri;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUser_image() {
        return user_image;
    }

    public void setUser_image(String user_image) {
        this.user_image = user_image;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    public String getStorename() {
        return storename;
    }

    public void setStorename(String storename) {
        this.storename = storename;
    }

    public Long getStore_id() {
        return store_id;
    }

    public void setStore_id(Long store_id) {
        this.store_id = store_id;
    }

    public String getCategoryname() {
        return categoryname;
    }

    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }

    public Long getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    public String getBrandname() {
        return brandname;
    }

    public void setBrandname(String brandname) {
        this.brandname = brandname;
    }

    public Long getBrand_id() {
        return brand_id;
    }

    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    public String getBrand_logo() {
        return brand_logo;
    }

    public void setBrand_logo(String brand_logo) {
        this.brand_logo = brand_logo;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getLikes() {
        return likes;
    }

    public void setLikes(Long likes) {
        this.likes = likes;
    }

    public Integer getPost_type() {
        return post_type;
    }

    public void setPost_type(Integer post_type) {
        this.post_type = post_type;
    }

    public Integer getOrder_in_category() {
        return order_in_category;
    }

    public void setOrder_in_category(Integer order_in_category) {
        this.order_in_category = order_in_category;
    }

    public Boolean getFavorited() {
        return favorited;
    }

    public void setFavorited(Boolean favorited) {
        this.favorited = favorited;
    }

    public Boolean getIsLocal() {
        return isLocal;
    }

    public void setIsLocal(Boolean isLocal) {
        this.isLocal = isLocal;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Boolean getLiked() {
        return liked;
    }

    public void setLiked(Boolean liked) {
        this.liked = liked;
    }

    public Boolean getDirty() {
        return dirty;
    }

    public void setDirty(Boolean dirty) {
        this.dirty = dirty;
    }

    public String getFeatured_in_globalID() {
        return featured_in_globalID;
    }

    public void setFeatured_in_globalID(String featured_in_globalID) {
        this.featured_in_globalID = featured_in_globalID;
    }

    public String getFeatured_in_title() {
        return featured_in_title;
    }

    public void setFeatured_in_title(String featured_in_title) {
        this.featured_in_title = featured_in_title;
    }

    public Boolean getRead() {
        return read;
    }

    public void setRead(Boolean read) {
        this.read = read;
    }

    // KEEP METHODS - put your custom methods here


    public boolean isLocal() {
        return isLocal;
    }
    // KEEP METHODS END

}
