package com.acquire.shopick.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.acquire.shopick.dao.RelatedProducts;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RELATED_PRODUCTS".
*/
public class RelatedProductsDao extends AbstractDao<RelatedProducts, Long> {

    public static final String TABLENAME = "RELATED_PRODUCTS";

    /**
     * Properties of entity RelatedProducts.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property GlobalID = new Property(1, String.class, "globalID", false, "GLOBAL_ID");
        public final static Property ProductglobalID = new Property(2, String.class, "productglobalID", false, "PRODUCTGLOBAL_ID");
    };


    public RelatedProductsDao(DaoConfig config) {
        super(config);
    }
    
    public RelatedProductsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RELATED_PRODUCTS\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"GLOBAL_ID\" TEXT," + // 1: globalID
                "\"PRODUCTGLOBAL_ID\" TEXT);"); // 2: productglobalID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RELATED_PRODUCTS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RelatedProducts entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String globalID = entity.getGlobalID();
        if (globalID != null) {
            stmt.bindString(2, globalID);
        }
 
        String productglobalID = entity.getProductglobalID();
        if (productglobalID != null) {
            stmt.bindString(3, productglobalID);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RelatedProducts readEntity(Cursor cursor, int offset) {
        RelatedProducts entity = new RelatedProducts( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // globalID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // productglobalID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RelatedProducts entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGlobalID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setProductglobalID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RelatedProducts entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RelatedProducts entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
