package com.acquire.shopick.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "RELATED_PRODUCTS".
 */
public class RelatedProducts {

    private Long id;
    private String globalID;
    private String productglobalID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RelatedProducts() {
    }

    public RelatedProducts(Long id) {
        this.id = id;
    }

    public RelatedProducts(Long id, String globalID, String productglobalID) {
        this.id = id;
        this.globalID = globalID;
        this.productglobalID = productglobalID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGlobalID() {
        return globalID;
    }

    public void setGlobalID(String globalID) {
        this.globalID = globalID;
    }

    public String getProductglobalID() {
        return productglobalID;
    }

    public void setProductglobalID(String productglobalID) {
        this.productglobalID = productglobalID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
