package com.acquire.shopick.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "STORE".
 */
public class Store {

    private Long id;
    private String name;
    private Float lat;
    private Float lon;
    private Long brand_id;
    private String phone;
    private String email;
    private String address;
    private String brand_logo;
    private Integer type;
    private String category;
    private Long category_id;
    private Long location_id;
    private String distance;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Store() {
    }

    public Store(Long id) {
        this.id = id;
    }

    public Store(Long id, String name, Float lat, Float lon, Long brand_id, String phone, String email, String address, String brand_logo, Integer type, String category, Long category_id, Long location_id, String distance) {
        this.id = id;
        this.name = name;
        this.lat = lat;
        this.lon = lon;
        this.brand_id = brand_id;
        this.phone = phone;
        this.email = email;
        this.address = address;
        this.brand_logo = brand_logo;
        this.type = type;
        this.category = category;
        this.category_id = category_id;
        this.location_id = location_id;
        this.distance = distance;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Float getLat() {
        return lat;
    }

    public void setLat(Float lat) {
        this.lat = lat;
    }

    public Float getLon() {
        return lon;
    }

    public void setLon(Float lon) {
        this.lon = lon;
    }

    public Long getBrand_id() {
        return brand_id;
    }

    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getBrand_logo() {
        return brand_logo;
    }

    public void setBrand_logo(String brand_logo) {
        this.brand_logo = brand_logo;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Long getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    public Long getLocation_id() {
        return location_id;
    }

    public void setLocation_id(Long location_id) {
        this.location_id = location_id;
    }

    public String getDistance() {
        return distance;
    }

    public void setDistance(String distance) {
        this.distance = distance;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
