package com.acquire.shopick.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TIPS".
 */
public class Tips {

    private Long id;
    private String title;
    private String description;
    private String globalID;
    private String image_url;
    private String category;
    private Long category_id;
    private String brand;
    private Long brand_id;
    private Boolean liked;
    private Boolean dirty;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Tips() {
    }

    public Tips(Long id) {
        this.id = id;
    }

    public Tips(Long id, String title, String description, String globalID, String image_url, String category, Long category_id, String brand, Long brand_id, Boolean liked, Boolean dirty) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.globalID = globalID;
        this.image_url = image_url;
        this.category = category;
        this.category_id = category_id;
        this.brand = brand;
        this.brand_id = brand_id;
        this.liked = liked;
        this.dirty = dirty;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getGlobalID() {
        return globalID;
    }

    public void setGlobalID(String globalID) {
        this.globalID = globalID;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Long getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public Long getBrand_id() {
        return brand_id;
    }

    public void setBrand_id(Long brand_id) {
        this.brand_id = brand_id;
    }

    public Boolean getLiked() {
        return liked;
    }

    public void setLiked(Boolean liked) {
        this.liked = liked;
    }

    public Boolean getDirty() {
        return dirty;
    }

    public void setDirty(Boolean dirty) {
        this.dirty = dirty;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
