package com.acquire.shopick.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TOP_CATEGORIES".
 */
public class TopCategories {

    private Long id;
    private String tag;
    private String name;
    private String category;
    private String color;
    private String image_url;
    private Long parent_category_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TopCategories() {
    }

    public TopCategories(Long id) {
        this.id = id;
    }

    public TopCategories(Long id, String tag, String name, String category, String color, String image_url, Long parent_category_id) {
        this.id = id;
        this.tag = tag;
        this.name = name;
        this.category = category;
        this.color = color;
        this.image_url = image_url;
        this.parent_category_id = parent_category_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public Long getParent_category_id() {
        return parent_category_id;
    }

    public void setParent_category_id(Long parent_category_id) {
        this.parent_category_id = parent_category_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
