package com.acquire.shopick.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Integer id;
    private String email;
    private String name;
    private String profileImage;
    private String coverImage;
    private Integer gender;
    private String instanceID;
    private String usercode;
    private String referred;
    private Long picks;
    private Long monthlyPicks;
    private String authentication_token;
    private Long rank;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public User() {
    }

    public User(Integer id) {
        this.id = id;
    }

    public User(Integer id, String email, String name, String profileImage, String coverImage, Integer gender, String instanceID, String usercode, String referred, Long picks, Long monthlyPicks, String authentication_token, Long rank) {
        this.id = id;
        this.email = email;
        this.name = name;
        this.profileImage = profileImage;
        this.coverImage = coverImage;
        this.gender = gender;
        this.instanceID = instanceID;
        this.usercode = usercode;
        this.referred = referred;
        this.picks = picks;
        this.monthlyPicks = monthlyPicks;
        this.authentication_token = authentication_token;
        this.rank = rank;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getProfileImage() {
        return profileImage;
    }

    public void setProfileImage(String profileImage) {
        this.profileImage = profileImage;
    }

    public String getCoverImage() {
        return coverImage;
    }

    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getInstanceID() {
        return instanceID;
    }

    public void setInstanceID(String instanceID) {
        this.instanceID = instanceID;
    }

    public String getUsercode() {
        return usercode;
    }

    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    public String getReferred() {
        return referred;
    }

    public void setReferred(String referred) {
        this.referred = referred;
    }

    public Long getPicks() {
        return picks;
    }

    public void setPicks(Long picks) {
        this.picks = picks;
    }

    public Long getMonthlyPicks() {
        return monthlyPicks;
    }

    public void setMonthlyPicks(Long monthlyPicks) {
        this.monthlyPicks = monthlyPicks;
    }

    public String getAuthentication_token() {
        return authentication_token;
    }

    public void setAuthentication_token(String authentication_token) {
        this.authentication_token = authentication_token;
    }

    public Long getRank() {
        return rank;
    }

    public void setRank(Long rank) {
        this.rank = rank;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
